stages:
  - check
  - build

check:
  stage: check
  image: rustlang/rust:nightly
  script:
    - cargo fmt --all -- --check
    - cargo clippy --all -- -D warnings

build:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose

test:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo test --verbose -- --nocapture
