stages:
  - check
  - build

format:
  stage: check
  image: rustlang/rust:nightly
  script:
    - cargo fmt --all -- --check
    - cargo clippy --all -- -D warnings

build-project:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose

unit-tests:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose -- --nocapture
