stages:
  - check
  - build
  - upload

variables:
  CACHIX_NAME: stu
  NIX_FLAGS: "--experimental-features 'nix-command flakes'"

format:
  stage: check
  image: rustlang/rust:nightly
  script:
    - cargo fmt --all -- --check
    - cargo clippy --all -- -D warnings

build-project:
  stage: build
  image: nixos/nix:latest
  script:
    - nix $(NIX_FLAGS) build

unit-tests:
  stage: build
  image: nixos/nix:latest
  script:
    - nix $(NIX_FLAGS) build .#test

cachix:
  stage: upload
  before_script:
    - nix-env -iA nixpkgs.cachix nixpkgs.bash
    - cachix use mycache
    - nix path-info --all > /tmp/store-path-pre-build
  script:
    - nix $(NIX_FLAGS) build
  after_script:
    - nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)' | cachix push $CACHIX_NAME
